[env:ttgo-t-beam-v1_2]
extends = env:esp32
board = ttgo-t-beam
build_flags =
	${common.build_flags}
	-D RADIOLIB_EXCLUDE_LR11X0=1
	-D RADIOLIB_EXCLUDE_SX126X=1
	-D RADIOLIB_EXCLUDE_SX128X=1
	-D TTGO_T_Beam_V1_2
build_src_filter =
	+<../src/>
	-<../src/lvgl_ui.cpp>
	-<../src/ui_dashboard.cpp>
	-<../src/ui_messaging.cpp>
	-<../src/ui_popups.cpp>
	-<../src/ui_settings.cpp>
	-<../src/lv_font_*.c>
	-<../src/lora_aprs_bg.c>
	-<../src/lora_aprs_logo.c>
	-<../src/map/>
lib_deps =
	${common.lib_deps}
	${common.display_libs}
	lewisxhe/XPowersLib @ 0.2.4
	adafruit/Adafruit SH110X @ 2.1.10